name: Build APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Assemble Project
      run: |
        npm init -y
        npm install @capacitor/core @capacitor/cli @capacitor/android
        mkdir -p www
        cp index.html style.css www/
        cp -r js www/
        npx cap init Atmospheres com.atmospheres.player --web-dir www
        npx cap add android
        npx cap sync android
        
        # Включаем разрешения на интернет и фоновую работу
        MANIFEST="android/app/src/main/AndroidManifest.xml"
        sed -i '/<application/i \    <uses-permission android:name="android.permission.INTERNET" />\n    <uses-permission android:name="android.permission.WAKE_LOCK" />\n    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />' $MANIFEST

    - name: Build Debug APK
      run: |
        cd android
        chmod +x gradlew
        ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: AtmospheresApp
        path: android/app/build/outputs/apk/debug/app-debug.apk
